---
title: "Storm Wave Analysis of the East Coast Low Event on June 3rd 2016"
author: "Blake Seers"
date: '`r format(Sys.Date(), "%d %B, %Y")`'
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Background

On the 4th of June, 2016, an East Coast Low [^1] impacted New South Wales, causing wave overtopping and severe erosion in several areas. This event was a very intense, low pressure system that brought over 100mm of rainfall in one hour at places along the east coast NSW. Widespread rainfall totals exceeded 250mm along most of the NSW coast, leading to 21 catchments experiencing flooding and nearly all of the east-flowing rivers being affected. Periods of sustained gale force winds (over 63km/h) were recorded along the coast, and the Sydney Harbour experienced wind gusts of 116km/h. This intense event also coincided with tides near the Highest Astronomical Tide, combined with pressure-induced sea-level anomalies, and large north-easterly waves, which resulted in local inundation of low-lying areas and widespread coastal erosion (See [Louis et. al.](https://www.mhl.nsw.gov.au/data/realtime/wave/docs//2016NSWCoastalConferenceLouisCourieletal_Final.pdf) for more information).

This analysis investigates the role that storm waves may have played in the damaging event.

[^1]: [Holland, G. J., Lynch, A. H., & Leslie, L. M. (1987). *Australian east-coast cyclones. Part I: Synoptic overview and case study. Monthly Weather Review, 115*(12), 3024-3036.](https://journals.ametsoc.org/doi/10.1175/1520-0493%281987%29115%3C3024%3AAECCPI%3E2.0.CO%3B2)